server:
  port: 5002
spring:
  application:
    name: TASK-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: TASK-SERVICE
      auto-index-creation: true
      uri: mongodb://localhost:27017/TASK-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka
